user: root
http_port: 80
max_clients: 200
system_packages:
  - nginx
  - git
  - curl
  - locales
  - nodejs
  - postgresql
  - openjdk-7-jre-headless
project_repo: https://github.com/devops-ru/continuous-delivery
project_dir: /var/www
project_root: "{{ project_dir }}/site"
locale: en_US.UTF-8

dbuser: dbuser
dbpassword: dbpassword
database: mydb

# Basic settings
postgresql_version: 9.3
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_databases:
  - name: "{{database}}"

# List of users to be created (optional)
postgresql_users:
  - name: "{{dbuser}}"
    pass: "{{dbpassword}}"
    encrypted: no

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: "{{dbuser}}"                   # user name
    db: "{{database}}"
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags



branch: master
flyway_root: /opt/flyway
flyway_config:
  database:
    host: localhost
    port: 5432
    dbms: postgesql
    name: "{{ dbuser }}"
    user: "{{ dbpassword }}"
    password: postgres
  schemas: public, myschema
flyway_locations: /var/www/site/migrations
