---
- hosts: app
  remote_user: root
  tasks:
  - name: prepare dir
    file: path={{ project_dir }} mode=0777 state=directory

  - name: pull app
    git: repo={{ project_repo }} dest={{ project_root }} version={{ branch }}

  - name: ensure nginx is running
    service: name=nginx state=started enabled=yes

  - name: prepare dir
    file: path={{ project_dir }} mode=0777 state=directory

  - name: flyway conf
    template: src=templates/flyway.conf.j2 dest={{ project_root }}/flyway.conf

  - name: write the nginx config file
    template: src=templates/site.cfg dest=/etc/nginx/sites-enabled/default
    notify:
      - restart nginx

  - name: test deploy
    shell: curl localhost:80

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
