---
- hosts: app
  remote_user: root
  vars:
    http_port: 80
    max_clients: 200
    system_packages:
      - nginx
      - git
      - curl
    project_repo: https://github.com/niquola/hellodevops.git
    project_dir: /var/www
    project_root: "{{ project_dir }}/site"
    branch: master
  tasks:
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ system_packages }}"

  - name: prepare dir
    file: path={{ project_dir }} mode=0777 state=directory

  - name: pull app
    git: repo={{ project_repo }} dest={{ project_root }} version={{ branch }}

  - name: site mode
    file: path={{ project_dir }} mode=0777 state=directory recurse=yes
